### ISSUE TITLE
Responsive menu

### ISSUE THREAD

**Issue by hjJunior** [BootstrapDash/StarAdmin-Free-Vue-Admin-Template#1]
Hi, first of all, congratulations about the beauty project!

However I found a little problem with responsive design, it happens on menu for mobile, so on mobile the left menu (sidebar) was hidden (but I need it :/ ) and this menu toggle its happen this
![image](https://user-images.githubusercontent.com/10780132/42029600-7bcd4db8-7aa6-11e8-9692-36c904fa65cf.png)

On tablet its look good, just could be exist a toggle to sidebar
![image](https://user-images.githubusercontent.com/10780132/42029610-858972d2-7aa6-11e8-8f33-a7e30fafdaa0.png)

Sidebar
![image](https://user-images.githubusercontent.com/10780132/42029622-91578eaa-7aa6-11e8-817f-09fcf09809e2.png)

**Comment by bootstrapdash-team** [comment]
@hjJunior We have fixed this issue in our latest update. Please check and feel free to reopen this thread if the issue still exists.
