### ISSUE TITLE
Installation security alert

### ISSUE THREAD

**Issue by swina** [BootstrapDash/StarAdmin-Free-Vue-Admin-Template#12]
This app is not safe and not updated (many packages are not supported anymore)

`
found 90 vulnerabilities (58 low, 11 moderate, 19 high, 2 critical) in 15883 scanned packages
  run `npm audit fix` to fix 32 of them.
  38 vulnerabilities require semver-major dependency updates.
  20 vulnerabilities require manual review. See the full report for details.`

**Comment by bootstrapdash-team** [comment]
Hi @swina ,

Apologies for the inconvenience caused. We are working on updating the outdated packages which can resolve the vulnerability issues as well. We will publish the updated code within two business days.

**Comment by bootstrapdash-team** [comment]
Hi @swina ,

We have updated the outdated packages. Please download the latest files and try again.
