### ISSUE TITLE
Implement to Laravel Project

### ISSUE THREAD

**Issue by alfanzain** [BootstrapDash/StarAdmin-Free-Vue-Admin-Template#6]
How to implement this template to Laravel project? 
What should I do?

I already copied components, package.json, and some javascripts.
But still not working.

**Comment by alfanzain** [comment]
HMMMMMMMMMMMMMMMMMMM

**Comment by khanzadimahdi** [comment]
i have used it with laravel. you have to remove all `lang` attributes from template tags.

**Comment by alfanzain** [comment]
> i have used it with laravel. you have to remove all `lang` attributes from template tags.

remove all `lang` ? just like that ?

**Comment by bootstrapdash-team** [comment]
Closing as the issue is inactive
